all:
	pdflatex main.tex
	bibtex main.aux
	pdflatex main.tex
	pdflatex main.tex
clean:
	rm -rfv main.pdf
	rm -rfv main.toc
	rm -rfv main.pdfsync
	rm -rfv main.lot
	rm -rfv main.log
	rm -rfv main.lof
	rm -rfv main.fls
	rm -rfv main.dvi
	rm -rfv main.aux
	rm -rfv main.fdb_latexmk
	rm -rfv main.brf
	rm -rfv main.bbl
	rm -rfv main.blg
	rm -rfv main.out
